language: go

go: "1.11"

cache:
  directories:
  - $GOPATH/pkg/dep
  - $GOPATH/pkg/mod

jobs:
  include:
  - &dep
    before_install:
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    include:
    - dep ensure -v -vendor-only
    script:
    - go get golang.org/x/lint/golint
    - go list ./... | xargs golint -set_exit_status
    if: type != 'pull_request'

  - &dep-test
    <<: *dep
    script:
    - go test -v ./...

  - <<: *dep-test
    go: '1.9'

  - <<: *dep-test
    go: '1.10'

  - <<: *dep-test
    go: 'master'

  - name: '1.11 with Modules'
    env:
    - GO111MODULE=on
    install:
    - go get -v
    script:
    - go test -v ./...
